server:
  port: 8080 # 后期该微服务多实例，端⼝从8080递增（10个以内）
Spring:
  application:
    name: rmq-pub
# 注册到Eureka注册中心
eureka:
  client:
    service-url:
      # 注册到集群，就把Eureka Server地址用逗号分割即可
      defaultZone: http://192.168.1.103:8761/eureka/,http://192.168.1.103:8762/eureka/
  instance:
    prefer-ip-address: true #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 不去检查es的健康状况
  health:
    elasticsearch:
      enabled: false
app:
  id: rmq-esb
#apollo:
#  # 环境配置中心地址(Euraka)
#  meta: http://192.168.1.184:8080
#  bootstrap:
#    enabled: true
#    namespaces: application
#    # 将配置提前到日志初始化之前
#    eagerLoad:
#      enabled: true
#  cache-dir: ~/opt/data

# rocketMQ配置
rocketmq:
  # nameserver地址
  name-server: 192.168.1.182:9876
  # 生产组名称
  producer:
    group: producer_grp_02


spring:
  data:
    #ES
    elasticsearch:
      cluster-nodes: 192.168.1.184:9300
      cluster-name: elasticsearch
  # druid&mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rmq_esb?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      ddl-auto: update
#      naming:
#        physical-strategy:
    show-sql: true
  # redis
  redis:
    host: 192.168.1.181
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池的最小空闲连接
        min-idle: 0
        # 连接池的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间
        max-wait: 30000
        # 连接超时时间
        timeout: 30000
# 将下划线字段转换为通过命名法
mybatis:
  configuration:
    map-underscore-to-camel-case: true
